# find one

GET https://bff.quaq.me/api/v1/files/63ea37c3c5ec024456cc63e8

###

# create one

POST https://bff.quaq.me/api/v1/files
Content-Type: application/json

{
    "name": "test",
    "url": "2",
    "type": "image",
    "size": 1000,
    "mime_type": "image/jpeg",
    "metadata": {
        "key": "value"
    }
}

###

# find one by url

GET http://localhost:5000/api/v1/files/url/1

###

# update one

PUT http://localhost:5000/api/v1/files/63b34032485edc50f1bdfa72
Content-Type: application/json

{
    "name": "test2",
    "url": "2",
    "type": "image2",
    "size": 2000,
    "mime_type": "image/png",
    "metadata": {
        "key": "value2"
    }
}

###

# delete one

DELETE http://localhost:5000/api/v1/files/63b34032485edc50f1bdfa72