# find one

GET http://bff.quaq.me/api/v1/interactions/63ea3d2fd8d22196c5a0a1a5

###

# create one
POST http://localhost:5000/api/v1/interactions
Content-Type: application/json

{
    "blocks": [
        {
            "type": "text",
            "text": "Hello world"
        }
    ],
    "data": ["some data"],
    "events": [
        {
            "type": "text",
            "text": "Hello world"
        }
    ],
    "metadata": {
        "some": "data"
    },
    "last_block_id": "some block id",
    "depth": 1,
    "locations": [
        {
            "type": "text",
            "text": "Hello world"
        }
    ],
    "template_id": "63b75045a43fc9f320321e9f",
    "publication_id": "63b75045a43fc9f320321e9f",
    "page_id": "63b75045a43fc9f320321e9f",
    "user_id": "63b75045a43fc9f320321e9f"
}

###

# find one by user id
GET http://localhost:5000/api/v1/interactions/user/63b75045a43fc9f320321e9f

###

# find one by page id
GET http://localhost:5000/api/v1/interactions/page/63b75045a43fc9f320321e9f


###

# find one by publication id
GET http://localhost:5000/api/v1/interactions/publication/63b75045a43fc9f320321e9f

###

PUT http://localhost:5000/api/v1/interactions/63b758b9aca8210f48db934b
Content-Type: application/json

{
    "blocks": [
        {
            "type": "text2",
            "text": "Hello world2"
        }
    ]
}