# find one

GET https://bff.quaq.com.br/page/63b754987d02f98b8692255e


###

# create one

POST https://bff.quaq.com.br/page
Content-Type: application/json

{
    "name": "page test",
    "url": "url/url12",
    "workspace_id": "63b34032485edc50f1bdfa72",
    "avatar_url": "url/url",
    "background_url": "url/url"
}

###

# find all

GET https://bff.quaq.com.br/page

###

# find one by url

GET https://bff.quaq.com.br/page/url/url21

###

# find all by workspace

GET https://bff.quaq.com.br/page/workspace/63b34032485edc50f1bdfa72

###

# update one

PUT https://bff.quaq.com.br/page/63b754987d02f98b8692255e
Content-Type: application/json

{
    "avatar_url": "https://images.unsplash.com/photo-1522124624696-7ea32eb9592c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=600&q=60"
}

###

# delete one

DELETE https://bff.quaq.com.br/page/63b75045a43fc9f320321e9f


