# find one

GET https://bff.quaq.me/api/v1/pages/63df08bef243bdc4870d6b09


###

# create one

POST https://bff.quaq.me/api/v1/pages
Content-Type: application/json

{
    "name": "felp's page",
    "url": "felp's page",
    "workspace_id": "63dd14cdc3a3b5901c1675ff",
    "avatar_url": "https://images.unsplash.com/photo-1522124624696-7ea32eb9592c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=600&q=60",
    "background_url": "https://images.unsplash.com/photo-1522124624696-7ea32eb9592c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=600&q=60"
}

###

# find all

GET https://bff.quaq.me/api/v1/pages

###

# find one by url

GET https://bff.quaq.me/api/v1/pages/url/first

###

# find all by workspace

GET https://bff.quaq.me/api/v1/pages/workspace/63dd14cdc3a3b5901c1675ff

###

# update one

PUT https://bff.quaq.me/api/v1/pages/63b754987d02f98b8692255e
Content-Type: application/json

{
    "workspace_id": "63d68863688c6d9d82a5f648"
}

###

# delete one

DELETE https://bff.quaq.me/api/v1/pages/63b75045a43fc9f320321e9f


# generate unique url

POST https://bff.quaq.me/api/v1/pages/generate_unique_url
Content-Type: application/json

{
    "name": "adm1"
}