# find one

GET http://localhost:5000/api/v1/pages/63b754987d02f98b8692255e


###

# create one

POST http://localhost:5000/api/v1/pages
Content-Type: application/json

{
    "name": "pagininha",
    "url": "pagininha",
    "workspace_id": "63d7c6424b1d81503bf6beb9",
    "avatar_url": "https://images.unsplash.com/photo-1522124624696-7ea32eb9592c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=600&q=60",
    "background_url": "https://images.unsplash.com/photo-1522124624696-7ea32eb9592c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=600&q=60"
}

###

# find all

GET http://localhost:5000/api/v1/pages

###

# find one by url

GET http://localhost:5000/api/v1/pages/url/first

###

# find all by workspace

GET http://localhost:5000/api/v1/pages/workspace/63d68863688c6d9d82a5f648

###

# update one

PUT http://localhost:5000/api/v1/pages/63b754987d02f98b8692255e
Content-Type: application/json

{
    "workspace_id": "63d68863688c6d9d82a5f648"
}

###

# delete one

DELETE http://localhost:5000/api/v1/pages/63b75045a43fc9f320321e9f


