# find one

GET https://bff.quaq.me/api/v1/pages/63e04850acfb6a691c18af63


###

# create one

POST https://bff.quaq.me/api/v1/pages
Content-Type: application/json

{
    "name": "demo positivo",
    "url": "positivodemo",
    "workspace_id": "63ea983fa852c6a2dc94a609",
    "avatar_url": "https://source.unsplash.com/featured/",
    "background_url": "https://source.unsplash.com/featured/"
}

###

# find all

GET https://bff.quaq.me/api/v1/pages

###

# find one by url

GET https://bff.quaq.me/api/v1/pages/url/first

###

# find all by workspace

GET https://bff.quaq.me/api/v1/pages/workspace/63dd14cdc3a3b5901c1675ff

###

# update one

PUT https://bff.quaq.me/api/v1/pages/63b754987d02f98b8692255e
Content-Type: application/json

{
    "workspace_id": "63d68863688c6d9d82a5f648"
}

###

# delete one

DELETE https://bff.quaq.me/api/v1/pages/63b75045a43fc9f320321e9f

###

# generate unique url

POST https://bff.quaq.me/api/v1/pages/generate_unique_url
Content-Type: application/json

{
    "name": "felp's page"
}