# get publications

GET http://localhost:5000/api/v1/publications/63d5c42a05e8266454c5170f

###

# create publications

POST http://localhost:5000/api/v1/publications
Content-Type: application/json

{
    "title": "title2",
    "blocks": [{}],
    "page_id": "63d66e73e933f0d739d70f0b"
}

###

# get many publications by template id

GET http://localhost:5000/api/v1/publications/template/1

###

# get many publications by page id

GET http://localhost:5000/api/v1/publications/page/1

###

# update publications

PUT http://localhost:5000/api/v1/publications/63d5c42a05e8266454c5170f
Content-Type: application/json

{
    "title": "title1",
    "blocks": {
        "1": {
            "id": "1",
            "type": "type",
            "content": "content"
        }
    }
}