# get publications

GET https://bff.quaq.me/api/v1/publications/63dfd2a7c861c288325bcc6d

###

# create publications

POST https://bff.quaq.me/api/v1/publications
Content-Type: application/json

{
    "title": "first publication",
    "blocks": [{}],
    "page_id": "63df08bef243bdc4870d6b09"
}

###

# get many publications by template id

GET https://bff.quaq.me/api/v1/publications/template/63dfd2d5c861c288325bcc6e

###

# get many publications by page id

GET https://bff.quaq.me/api/v1/publications/page/1

###

# update publications

PUT https://bff.quaq.me/api/v1/publications/63dfd2a7c861c288325bcc6d
Content-Type: application/json

{
    "template_id": "63dfd2d5c861c288325bcc6e"  
}