# get publications

GET http://localhost:5000/api/v1/publications/63ae052efbbce66bbc152487

###

# create publications

POST http://localhost:5000/api/v1/publications
Content-Type: application/json

{
    "title": "title",
    "blocks": {},
    "template_id": "63ae052efbbce66bbc152487",
    "page_id": "63ae052efbbce66bbc152487"
}

###

# get many publications by template id

GET http://localhost:5000/api/v1/publications/template/1

###

# get many publications by page id

GET http://localhost:5000/api/v1/publications/page/1

###

# update publications

PUT http://localhost:5000/api/v1/publications/63920eab9b5c95524c8205ed
Content-Type: application/json

{
    "title": "title1",
    "blocks": {
        "1": {
            "id": "1",
            "type": "type",
            "content": "content"
        }
    }
}