# get templates

GET https://bff.quaq.me/api/v1/templates/63d91f6ecf6a7076d3a019f1

###

POST https://bff.quaq.me/api/v1/templates
Content-Type: application/json

{
  "name": "felp's template",
  "url": "templateteste",
  "shortcut_image": "https://images.unsplash.com/photo-1522124624696-7ea32eb9592c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=600&q=60",
  "shortcut_size": "https://images.unsplash.com/photo-1522124624696-7ea32eb9592c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=600&q=60",
  "current_publication_id": "63e048a4acfb6a691c18af64",
  "number_of_new_interactions": 1,
  "page_id": "63e04850acfb6a691c18af63"
}

###

# get templates by url

GET https://bff.quaq.me/api/v1/templates/url/testing

###

# get many templates by page id

GET https://bff.quaq.me/api/v1/templates/page/63df08bef243bdc4870d6b09

###

PUT https://bff.quaq.me/api/v1/templates/63d91f6ecf6a7076d3a019f1
Content-Type: application/json

{
  "shortcut_size": "small"
}

###

# delete one templates

DELETE https://bff.quaq.me/api/v1/templates/1ead50e3-c81b-4a64-87da-a1ff0f2e6b54

###

# get unique url

POST https://bff.quaq.me/api/v1/templates/generate_unique_url
Content-Type: application/json

{ 
  "title": "testing",
  "page_id": "63d2f4dd092cd140517d49c4"
}