# get template

GET https://bff.quaq.com.br/template/63ae050ffbbce66bbc152486

###

POST https://bff.quaq.com.br/template
Content-Type: application/json

{
    "name": "name",
    "url": "url",
    "shortcut_image": "shortcutImage",
    "shortcut_size": "shortcutSize",
    "current_publication_id": "63ae050ffbbce66bbc152486",
    "number_of_new_interactions": 1,
    "facebook_pixel_id": "63ae050ffbbce66bbc152486",
    "page_id": "63ae050ffbbce66bbc152486"
}

###

# get template by url

GET https://bff.quaq.com.br/template/url/url

###

# get many template by page id

GET https://bff.quaq.com.br/template/page/63ae050ffbbce66bbc152486

###

PUT https://bff.quaq.com.br/template/63ae050ffbbce66bbc152486
Content-Type: application/json

{
    "name": "name 2",
    "url": "url",
    "shortcut_image": "shortcutImage",
    "shortcut_size": "shortcutSize",
    "current_publication_id": "1",
    "number_of_new_interactions": 1,
    "page_id": "1",
    "facebook_pixel_id": "1"
}

###

# delete one template

DELETE https://bff.quaq.com.br/template/1ead50e3-c81b-4a64-87da-a1ff0f2e6b54

###

