# find one

GET http://localhost:5000/api/v1/workspaces/63d91e6acf6a7076d3a019ee

###

# create one

POST https://bff.quaq.me/api/v1/workspaces
Content-Type: application/json

{
  "name": "felp's world",
  "avatar_url": "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1222&q=80",
  "user_id": "63d26f06ea1e68c873e97ab2",
  "slug": "teste",
  "services": [
    {
      "name": "My Service",
      "description": "My Service Description"
    }
  ]
}

###

# update one

PUT  http://localhost:5000/api/v1/workspaces/63b7543e7d02f98b8692255d
Content-Type: application/json

{
  "name": "My Workspaces2",
  "avatar_url": "http://example.com/avatar2.png",
  "services": [
    {
      "name": "My Service2",
      "description": "My Service Description"
    }
  ]
}

###

# delete one

DELETE http://localhost:5000/api/v1/workspaces/63b7543e7d02f98b8692255d


###

# get may by user id

GET http://bff.quaq.me/api/v1/workspaces/user/63d26f06ea1e68c873e97ab2