# find one

GET https://bff.quaq.me/api/v1/workspaces/63d91e6acf6a7076d3a019ee

###

# create one

POST https://bff.quaq.me/api/v1/workspaces
Content-Type: application/json

{
  "name": "positivo demo",
  "avatar_url": "https://source.unsplash.com/featured/",
  "user_id": "63ea90f6d2cb853f3cb0f740",
  "slug": "positivodemo",
  "services": [
    {
      "name": "My Service",
      "description": "My Service Description"
    }
  ]
}

###

# update one

PUT  https://bff.quaq.me/api/v1/workspaces/63dd14cdc3a3b5901c1675ff
Content-Type: application/json

{
  "slug": "felpsworld"
}

###

# delete one

DELETE https://bff.quaq.me/api/v1/workspaces/63b7543e7d02f98b8692255d


###

# get many by user id

GET http://bff.quaq.me/api/v1/workspaces/user/63d26f06ea1e68c873e97ab2

###

# find one by slug

GET http://bff.quaq.me/api/v1/workspaces/slug/felpsworld